name: Docstring Check

on: [push, pull_request]

jobs:
  docstring:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install interrogate
      run: |
        python -m pip install --upgrade pip
        pip install interrogate
        
    - name: Run docstring check
      run: |
        interrogate -vinmMI --ignore-init-method --ignore-module --ignore-nested-functions --ignore-regex "__repr__" -f 60 audio2face/